In [24]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import pandas as pd
import cv2
import matplotlib.pyplot as plt

In [3]:
train=pd.read_csv('archive/sign_mnist_test.csv')
test=pd.read_csv('archive/sign_mnist_test.csv')
train

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,6,149,149,150,150,150,151,151,150,151,...,138,148,127,89,82,96,106,112,120,107
1,5,126,128,131,132,133,134,135,135,136,...,47,104,194,183,186,184,184,184,182,180
2,10,85,88,92,96,105,123,135,143,147,...,68,166,242,227,230,227,226,225,224,222
3,0,203,205,207,206,207,209,210,209,210,...,154,248,247,248,253,236,230,240,253,255
4,3,188,191,193,195,199,201,202,203,203,...,26,40,64,48,29,46,49,46,46,53
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7167,1,135,119,108,102,105,99,61,103,121,...,108,112,116,114,118,180,184,176,167,163
7168,12,157,159,161,164,166,166,171,174,175,...,213,213,213,214,213,211,210,210,209,208
7169,2,190,191,190,191,190,190,192,192,191,...,216,215,213,214,214,213,210,211,209,208
7170,4,201,205,208,209,214,216,218,223,226,...,112,169,255,255,237,113,91,67,70,63


In [4]:
tungtungtung=tf.convert_to_tensor(train.drop('label',axis=1))
tungtungtung

2026-03-20 14:43:47.762834: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M3
2026-03-20 14:43:47.762854: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2026-03-20 14:43:47.762857: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2026-03-20 14:43:47.762871: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2026-03-20 14:43:47.762879: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


<tf.Tensor: shape=(7172, 784), dtype=int64, numpy=
array([[149, 149, 150, ..., 112, 120, 107],
       [126, 128, 131, ..., 184, 182, 180],
       [ 85,  88,  92, ..., 225, 224, 222],
       ...,
       [190, 191, 190, ..., 211, 209, 208],
       [201, 205, 208, ...,  67,  70,  63],
       [173, 174, 173, ..., 195, 193, 192]])>

In [5]:
trainlabel= tf.convert_to_tensor(train['label'],dtype=tf.float32)
trainlabel

<tf.Tensor: shape=(7172,), dtype=float32, numpy=array([ 6.,  5., 10., ...,  2.,  4.,  2.], dtype=float32)>

In [6]:
from sklearn.preprocessing import MinMaxScaler
minmax=MinMaxScaler()
tungtungtung=minmax.fit_transform(tungtungtung)

In [32]:
validation, train=keras.utils.split_dataset(tungtungtung, left_size=0.2)
validation

<_PrefetchDataset element_spec=TensorSpec(shape=(784,), dtype=tf.float64, name=None)>

In [ ]:
model=keras.Sequential([
    layers.Conv2D(),
    layers.MaxPool2D(),
    layers.Conv2D(),
    layers.MaxPool2D(),
    layers.Conv2D(),
    layers.Conv2D(),
    layers.Conv2D(),
    layers.MaxPool2D(),
    layers.
])